name: build

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build:
    uses: charmbracelet/meta/.github/workflows/build.yml@main
    secrets:
      gh_pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
